# Generated by Django 5.2.6 on 2025-10-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('teacher', 'Teacher')], default='user', max_length=10),
        ),
    ]
