# Generated by Django 5.2.6 on 2025-10-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_student_user_alter_student_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group', to='courses.group'),
        ),
    ]
